name: C# CI
on:
  push:
    branches:
      - main
      - steps/01-gather-metrics
      - steps/02-treat-warnings-as-errors
      - steps/03-kill-mutants
      - steps/04-improve-tests-readability 
      - steps/05-approve-everything
      - steps/06-properties
      - steps/07-architecture-tests
      - steps/08-use-cases
      - steps/09-tell-dont-ask
      - steps/10-commands
      - steps/11-avoid-exceptions
      - steps/12-event-sourcing
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build
        working-directory: ./c#
        run: | 
          dotnet tool install --global dotnet-coverage
          dotnet build
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./c#
          args: >
            -Dsonar.organization=ythirion
            -Dsonar.projectKey=ythirion_refactoring-du-bouchonnois
            -Dsonar.cs.vscoveragexml.reportsPaths=coverage.xml
            -Dsonar.verbose=true